### ISSUE TITLE
unicode test fails

### ISSUE THREAD

**Issue by aaronmcdaid** [kunegis/stu#2]
(Update: now I've confused myself - maybe there is no issue after all! I'll message again shortly)

```
 $ ./mktest unicode
__________________________________
 cd unicode
../../stu 
./mktest: *** Test 'unicode' should have returned 0, but returned 1
./mktest: *** Target 'A' was not built
../../stu 
  ./mktest: *** Second invocation did no result in 'Nothing to be done'
__________________________________
./mktest: *** The following tests failed:
unicode
```

Looking at the test itself, it expects a file to already exist called `世界`, which it then copies to `jérôme.data` and then to `A`. Is this correct? And therefore should the file `世界` be included in the repository?

I'll submit a pull request, where I'll add a fix, `touch 世界`

**Comment by aaronmcdaid** [comment]
An update.

The file `世界` is part of the repo. But, as far as I can see, any called to `mktest` deletes much of the contents of the test directory. Therefore, this file needs to be recreated again in the recipe

(This is my first time using `stu`, apologies for any misunderstanding!)

**Comment by kunegis** [comment]
Hi Aaron

thanks for the notice! 

I guess it was not a good idea to store UTF-8 files in git. 

BTW, ./mktest should not delete the Chinese file in principle.  I guess that during checkout of the project, that UTF-8-named file gets lost.  The new version doesn't have the UTF-8 in git.

I amended your fix to generate the Chinese file before Stu invocation, for a more complete test.  (EXEC and main.stu use the same encoding)

Cheers
Jérôme
